"""Project-specific metadata for the local runtime."""

from agents.models import ProjectSpec

PROJECT_CONTEXT = {'repo_name': 'Synthesis-Markee',
 'project_name': 'Repo Steward Agent',
 'track': 'Markee',
 'pitch': 'A repo-stewarding agent that drafts updates, messages, and build-story '
          'artifacts for public codebases while maintaining a verifiable audit trail.',
 'idea_titles': ['Autonomous OSS Improvement Messenger',
                 'Onchain Build Story Distributor',
                 'Revenue-Aware GitHub Growth Loop'],
 'architecture_summary': 'A repo-stewarding agent drafts updates, messages, and '
                         'build-story artifacts for public codebases while maintaining '
                         'a verifiable audit trail. The contract side stores campaign '
                         'receipts and payout policy state while Python tooling '
                         'assembles GitHub-ready deliverables.',
 'overlap_targets': ['OpenServ',
                     'Filecoin',
                     'ENS',
                     'Bankr Gateway',
                     'Octant',
                     'Ampersend'],
 'primary_contract_name': 'RepoStewardCampaign',
 'primary_python_module': 'repo_steward',
 'category': 'autonomy',
 'daily_budget_usd': 114,
 'per_action_budget_usd': 28,
 'cooldown_seconds': 900,
 'discovery_inputs': [{'name': 'problem_signal',
                       'description': 'Discovery inputs used to detect a real '
                                      'opportunity.'},
                      {'name': 'policy_envelope',
                       'description': 'Budget, caps, and cooldown policy state.'},
                      {'name': 'execution_bundle',
                       'description': 'Dry-run and live execution bundle metadata.'},
                      {'name': 'receipts',
                       'description': 'Submission notes and final verification '
                                      'digests.'}],
 'live_demo_steps': ['Copy .env.example to .env and fill the required keys.',
                     'Deploy the contract with forge script script/Deploy.s.sol '
                     '--broadcast for RepoStewardCampaign.',
                     'Run python3 scripts/run_agent.py to produce a dry run for '
                     'repo_steward.',
                     'Set LIVE_MODE=true and rerun python3 scripts/run_agent.py with '
                     'real credentials.',
                     'Run python3 scripts/render_submission.py and attach TxIDs plus '
                     'repo links.'],
 'partners': [{'name': 'Markee',
               'docs_url': 'https://markee.xyz/',
               'env_vars': ['MARKEE_API_KEY', 'MARKEE_MESSAGE_URL'],
               'endpoint_env': 'MARKEE_MESSAGE_URL',
               'action_kind': 'rest_json',
               'purpose': 'Publish GitHub-adjacent build stories and repo messages.'},
              {'name': 'OpenServ',
               'docs_url': 'https://docs.openserv.ai/',
               'env_vars': ['OPENSERV_API_KEY', 'OPENSERV_AGENT_URL'],
               'endpoint_env': 'OPENSERV_AGENT_URL',
               'action_kind': 'rest_json',
               'purpose': 'Dispatch jobs and expose swarm service endpoints.'},
              {'name': 'Filecoin',
               'docs_url': 'https://docs.filecoin.cloud/',
               'env_vars': ['FILECOIN_API_TOKEN', 'FILECOIN_UPLOAD_URL'],
               'endpoint_env': 'FILECOIN_UPLOAD_URL',
               'action_kind': 'file_upload',
               'purpose': 'Persist proofs, logs, and evidence bundles offchain.'},
              {'name': 'ENS',
               'docs_url': 'https://docs.ens.domains/',
               'env_vars': ['ENS_NAME'],
               'endpoint_env': '',
               'action_kind': 'contract_call',
               'purpose': 'Publish human-readable coordination and identity receipts.'},
              {'name': 'Bankr Gateway',
               'docs_url': 'https://bankr.bot/',
               'env_vars': ['BANKR_API_KEY',
                            'BANKR_CHAT_COMPLETIONS_URL',
                            'BANKR_MODEL'],
               'endpoint_env': 'BANKR_CHAT_COMPLETIONS_URL',
               'action_kind': 'rest_json',
               'purpose': 'Route inference through cost-aware model selection.'},
              {'name': 'Octant',
               'docs_url': 'https://octant.app/',
               'env_vars': ['OCTANT_SIGNAL_URL'],
               'endpoint_env': 'OCTANT_SIGNAL_URL',
               'action_kind': 'rest_json',
               'purpose': 'Publish scored public-goods signals and DPI artifacts.'},
              {'name': 'Ampersend',
               'docs_url': 'https://docs.ampersend.ai/',
               'env_vars': ['AMPERSEND_API_KEY', 'AMPERSEND_PAYMENT_URL'],
               'endpoint_env': 'AMPERSEND_PAYMENT_URL',
               'action_kind': 'rest_json',
               'purpose': 'Bundle payment and transport metadata for downstream '
                          'agents.'}],
 'actions': [{'id': 'markee_repo_message',
              'target': 'markee',
              'purpose': 'Use Markee for a bounded action in this repo.',
              'partner': 'Markee',
              'action_kind': 'rest_json',
              'max_amount_usd': 5,
              'priority': 100,
              'sensitivity': 'low',
              'notes': ['Call Markee only after a dry-run artifact exists.',
                        'Use https://markee.xyz/ for credential setup.']},
             {'id': 'openserv_job_dispatch',
              'target': 'openserv',
              'purpose': 'Use OpenServ for a bounded action in this repo.',
              'partner': 'OpenServ',
              'action_kind': 'rest_json',
              'max_amount_usd': 10,
              'priority': 95,
              'sensitivity': 'medium',
              'notes': ['Call OpenServ only after a dry-run artifact exists.',
                        'Use https://docs.openserv.ai/ for credential setup.']},
             {'id': 'filecoin_proof_store',
              'target': 'filecoin',
              'purpose': 'Use Filecoin for a bounded action in this repo.',
              'partner': 'Filecoin',
              'action_kind': 'file_upload',
              'max_amount_usd': 20,
              'priority': 90,
              'sensitivity': 'medium',
              'notes': ['Call Filecoin only after a dry-run artifact exists.',
                        'Use https://docs.filecoin.cloud/ for credential setup.']},
             {'id': 'ens_ens_publish',
              'target': 'ens',
              'purpose': 'Use ENS for a bounded action in this repo.',
              'partner': 'ENS',
              'action_kind': 'contract_call',
              'max_amount_usd': 5,
              'priority': 85,
              'sensitivity': 'low',
              'notes': ['Call ENS only after a dry-run artifact exists.',
                        'Use https://docs.ens.domains/ for credential setup.']},
             {'id': 'bankr_gateway_compute_route',
              'target': 'bankr_gateway',
              'purpose': 'Use Bankr Gateway for a bounded action in this repo.',
              'partner': 'Bankr Gateway',
              'action_kind': 'rest_json',
              'max_amount_usd': 10,
              'priority': 80,
              'sensitivity': 'high',
              'notes': ['Call Bankr Gateway only after a dry-run artifact exists.',
                        'Use https://bankr.bot/ for credential setup.']},
             {'id': 'octant_signal_publish',
              'target': 'octant',
              'purpose': 'Use Octant for a bounded action in this repo.',
              'partner': 'Octant',
              'action_kind': 'rest_json',
              'max_amount_usd': 25,
              'priority': 75,
              'sensitivity': 'medium',
              'notes': ['Call Octant only after a dry-run artifact exists.',
                        'Use https://octant.app/ for credential setup.']},
             {'id': 'ampersend_settlement_bundle',
              'target': 'ampersend',
              'purpose': 'Use Ampersend for a bounded action in this repo.',
              'partner': 'Ampersend',
              'action_kind': 'rest_json',
              'max_amount_usd': 25,
              'priority': 70,
              'sensitivity': 'medium',
              'notes': ['Call Ampersend only after a dry-run artifact exists.',
                        'Use https://docs.ampersend.ai/ for credential setup.']}]}


def build_project_spec() -> ProjectSpec:
    """Return the repository-specific project metadata."""
    return ProjectSpec.from_dict(PROJECT_CONTEXT)
